// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #7 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      vulnerable
 * FUNCTION:      withdraw
 * VULNERABILITY: GENERIC
 * SEVERITY:      medium
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: withdraw() — Z3 SAT with concrete values, invariant 'balance_conservation' violated. At
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys malicious contract with receive()/fallback()
 *   2. 2. Attacker deposits 290.10 ETH → withdraw() records balance
 *   3. 3. Attacker calls withdraw()
 *   4. 4. Contract sends 290.10 ETH via .call{value} BEFORE updating state
 *   5. 5. Attacker's receive() re-enters withdraw()
 *   6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented
 *   7. 7. Contract sends 290.10 ETH AGAIN
 *   8. 8. State finally updates — but attacker already received 2x
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 03:45
 */

import "../../vulnerable.sol";

contract PoC_Generic_vulnerable_Test is Test {
    vulnerable public target;

    function setUp() public {
        target = new vulnerable();
    }

    function test_exploit() public {
        console.log("=== AGL PoC: Generic Exploit for vulnerable.withdraw ===");

        // Reconstructed attack steps:
        // 1. 1. Attacker deploys malicious contract with receive()/fallback()
        // 2. 2. Attacker deposits 290.10 ETH → withdraw() records balance
        // 3. 3. Attacker calls withdraw()
        // 4. 4. Contract sends 290.10 ETH via .call{value} BEFORE updating state
        // 5. 5. Attacker's receive() re-enters withdraw()
        // 6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented

        // Z3 Counterexample (triggering inputs):
        // balance_sender = 580084190969562738321
        // contract_balance = 2
        // withdraw2 = 290103009083993347913
        // withdraw1 = 290103009083993347913
        // amount = 290103009083993347913

        // TODO: Implement specific exploit based on the attack steps above
        console.log("[INFO] Vulnerability detected -- manual PoC construction recommended");
        console.log("  Function: withdraw");
        console.log("  See attack steps in comments above");
    }
}
