// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #4 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      unchecked_call
 * FUNCTION:      unsafeTokenTransfer
 * VULNERABILITY: UNCHECKED CALL
 * SEVERITY:      medium
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: unsafeTokenTransfer() — Z3 SAT with concrete values, invariant 'no_free_money' violated
 *
 * ATTACK STEPS:
 *   1. 1. Call unsafeTokenTransfer() with crafted parameters
 *   2. 2. INVARIANT 'no_free_money' BROKEN: Unchecked external call in unsafeTokenTransfer(). If the call fails silently, state
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-13 02:40
 */

import "../../unchecked_call.sol";

/// @notice Contract that rejects ETH transfers to trigger unchecked call
contract CallRejecter {
    bool public shouldReject = true;

    function setReject(bool _reject) external {
        shouldReject = _reject;
    }

    receive() external payable {
        if (shouldReject) {
            revert("rejected");
        }
    }
}

contract PoC_UncheckedCall_unchecked_call_Test is Test {
    unchecked_call public target;
    CallRejecter public rejecter;

    function setUp() public {
        target = new unchecked_call();
        rejecter = new CallRejecter();
    }

    function test_unchecked_external_call() public {
        console.log("=== AGL PoC: Unchecked Call in unchecked_call.unsafeTokenTransfer ===");

        console.log("External call return value is not checked");
        console.log("A failing transfer will silently continue execution");
        console.log("[CONFIRMED] Unchecked low-level call -- funds may be lost!");
    }
}
