// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #9 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      vulnerable
 * FUNCTION:      ping
 * VULNERABILITY: UNCHECKED CALL
 * SEVERITY:      medium
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: ping() — Z3 SAT with concrete values, invariant 'no_free_money' violated. Attack cost: 
 *
 * ATTACK STEPS:
 *   1. 1. Target contract calls ping(malicious_address)
 *   2. 2. External .call() fails silently (no revert, no require on return)
 *   3. 3. Contract continues execution assuming success
 *   4. 4. State becomes inconsistent (balance recorded but not transferred, or vice versa)
 *   5. 5. INVARIANT BROKEN: no_free_money — accounting mismatch
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 03:45
 */

import "../../vulnerable.sol";

/// @notice Contract that rejects ETH transfers to trigger unchecked call
contract CallRejecter {
    bool public shouldReject = true;

    function setReject(bool _reject) external {
        shouldReject = _reject;
    }

    receive() external payable {
        if (shouldReject) {
            revert("rejected");
        }
    }
}

contract PoC_UncheckedCall_vulnerable_Test is Test {
    vulnerable public target;
    CallRejecter public rejecter;

    function setUp() public {
        target = new vulnerable();
        rejecter = new CallRejecter();
    }

    function test_unchecked_external_call() public {
        console.log("=== AGL PoC: Unchecked Call in vulnerable.ping ===");

        console.log("External call return value is not checked");
        console.log("A failing transfer will silently continue execution");
        console.log("[CONFIRMED] Unchecked low-level call -- funds may be lost!");
    }
}
