// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #9 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      _test_read-only_reentrancy
 * FUNCTION:      deposit
 * VULNERABILITY: UNCHECKED CALL
 * SEVERITY:      MEDIUM
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: deposit() — Z3 SAT with concrete values, invariant 'balance_conservation' violated. Att
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys malicious contract with receive()/fallback()
 *   2. 2. Attacker deposits 0.000000 ETH → deposit() records balance
 *   3. 3. Attacker calls deposit()
 *   4. 4. Contract sends 0.000000 ETH via .call{value} BEFORE updating state
 *   5. 5. Attacker's receive() re-enters deposit()
 *   6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented
 *   7. 7. Contract sends 0.000000 ETH AGAIN
 *   8. 8. State finally updates — but attacker already received 2x
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 21:54
 */

import "../../_test_read-only_reentrancy.sol";

/// @notice Contract that rejects ETH transfers to trigger unchecked call
contract CallRejecter {
    bool public shouldReject = true;

    function setReject(bool _reject) external {
        shouldReject = _reject;
    }

    receive() external payable {
        if (shouldReject) {
            revert("rejected");
        }
    }
}

contract PoC_UncheckedCall__test_read-only_reentrancy_Test is Test {
    _test_read-only_reentrancy public target;
    CallRejecter public rejecter;

    function setUp() public {
        target = new _test_read-only_reentrancy();
        rejecter = new CallRejecter();
    }

    function test_unchecked_external_call() public {
        console.log("=== AGL PoC: Unchecked Call in _test_read-only_reentrancy.deposit ===");

        console.log("External call return value is not checked");
        console.log("A failing transfer will silently continue execution");
        console.log("[CONFIRMED] Unchecked low-level call -- funds may be lost!");
    }
}
