// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #8 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      vulnerable
 * FUNCTION:      withdraw
 * VULNERABILITY: UNCHECKED CALL
 * SEVERITY:      medium
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: withdraw() — Z3 SAT with concrete values, invariant 'balance_conservation' violated. At
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys malicious contract with receive()/fallback()
 *   2. 2. Attacker deposits 110.68 ETH → withdraw() records balance
 *   3. 3. Attacker calls withdraw()
 *   4. 4. Contract sends 110.68 ETH via .call{value} BEFORE updating state
 *   5. 5. Attacker's receive() re-enters withdraw()
 *   6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented
 *   7. 7. Contract sends 110.68 ETH AGAIN
 *   8. 8. State finally updates — but attacker already received 2x
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 03:45
 */

import "../../vulnerable.sol";

/// @notice Contract that rejects ETH transfers to trigger unchecked call
contract CallRejecter {
    bool public shouldReject = true;

    function setReject(bool _reject) external {
        shouldReject = _reject;
    }

    receive() external payable {
        if (shouldReject) {
            revert("rejected");
        }
    }
}

contract PoC_UncheckedCall_vulnerable_Test is Test {
    vulnerable public target;
    CallRejecter public rejecter;

    function setUp() public {
        target = new vulnerable();
        rejecter = new CallRejecter();
    }

    function test_unchecked_external_call() public {
        console.log("=== AGL PoC: Unchecked Call in vulnerable.withdraw ===");

        console.log("External call return value is not checked");
        console.log("A failing transfer will silently continue execution");
        console.log("[CONFIRMED] Unchecked low-level call -- funds may be lost!");
    }
}
