// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #3 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      timestamp_lottery
 * FUNCTION:      play
 * VULNERABILITY: UNCHECKED CALL
 * SEVERITY:      MEDIUM
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: play() — Z3 SAT with concrete values, invariant 'balance_conservation' violated. Attack
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys malicious contract with receive()/fallback()
 *   2. 2. Attacker deposits 9444.73 ETH → play() records balance
 *   3. 3. Attacker calls play()
 *   4. 4. Contract sends 9444.73 ETH via .call{value} BEFORE updating state
 *   5. 5. Attacker's receive() re-enters play()
 *   6. 6. require(balances[attacker] >= amount) PASSES — balance not yet decremented
 *   7. 7. Contract sends 9444.73 ETH AGAIN
 *   8. 8. State finally updates — but attacker already received 2x
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 21:54
 */

import "../../timestamp_lottery.sol";

/// @notice Contract that rejects ETH transfers to trigger unchecked call
contract CallRejecter {
    bool public shouldReject = true;

    function setReject(bool _reject) external {
        shouldReject = _reject;
    }

    receive() external payable {
        if (shouldReject) {
            revert("rejected");
        }
    }
}

contract PoC_UncheckedCall_timestamp_lottery_Test is Test {
    timestamp_lottery public target;
    CallRejecter public rejecter;

    function setUp() public {
        target = new timestamp_lottery();
        rejecter = new CallRejecter();
    }

    function test_unchecked_external_call() public {
        console.log("=== AGL PoC: Unchecked Call in timestamp_lottery.play ===");

        console.log("External call return value is not checked");
        console.log("A failing transfer will silently continue execution");
        console.log("[CONFIRMED] Unchecked low-level call -- funds may be lost!");
    }
}
