// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #7 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      delegatecall_proxy
 * FUNCTION:      execute
 * VULNERABILITY: UNCHECKED CALL
 * SEVERITY:      high
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: execute() — Z3 SAT with concrete values, invariant 'no_free_money' violated. Attack cos
 *
 * ATTACK STEPS:
 *   1. 1. Call execute() with crafted parameters
 *   2. 2. INVARIANT 'no_free_money' BROKEN: Unchecked external call in execute(). If the call fails silently, state becomes inc
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-13 02:40
 */

import "../../delegatecall_proxy.sol";

/// @notice Contract that rejects ETH transfers to trigger unchecked call
contract CallRejecter {
    bool public shouldReject = true;

    function setReject(bool _reject) external {
        shouldReject = _reject;
    }

    receive() external payable {
        if (shouldReject) {
            revert("rejected");
        }
    }
}

contract PoC_UncheckedCall_delegatecall_proxy_Test is Test {
    delegatecall_proxy public target;
    CallRejecter public rejecter;

    function setUp() public {
        target = new delegatecall_proxy();
        rejecter = new CallRejecter();
    }

    function test_unchecked_external_call() public {
        console.log("=== AGL PoC: Unchecked Call in delegatecall_proxy.execute ===");

        console.log("External call return value is not checked");
        console.log("A failing transfer will silently continue execution");
        console.log("[CONFIRMED] Unchecked low-level call -- funds may be lost!");
    }
}
